title: "Concerned;Carrot"
description:
lang: 
timezone:
theme: minima

author:
  name: "ConcernedCarrot"
  email:
  github_username:

show_excerpts: true
paginate: 10
paginate_path: "/page:num/"
baseurl: ""

minima:
  skin: auto

plugins:
  - jekyll-paginate

header_pages:
  - index.md            

giscus:
  repo: "ConcernedCarrot/ConcernedCarrot.github.io"
  repo_id: "R_kgDOQES6jg"
  category: "Announcements"
  category_id: "DIC_kwDOQES6js4Cwwfh"
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "preferred_color_scheme"
  lang: 
