title: "Concerned;Carrot"
description: 
lang: 
timezone: 
theme: minima
author:
  name: ConcernedCarrot
  email: 
  github_username: 
minima:
  skin: auto
show_excerpts: true
paginate: 10
paginate_path: "/page:num/"
# For a user/organization site, leave both url and baseurl blank or set url to your site later.
# url: "https://concernedcarrot.github.io"
baseurl: ""
plugins:
  - jekyll-paginate

  giscus:
  repo: "ConcernedCarrot/ConcernedCarrot.github.io"
  repo_id: "R_kgDOQES6jg"
  category: "Announcements"         
  category_id: "DIC_kwDOQES6js4Cwwfh"
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "preferred_color_scheme"
  lang: "en"                        
