title: "Concerned;Carrot"
description: "心配する人参"

author: ConcernedCarrot

social_links:
  - name: Github
    url: https://github.com/ConcernedCarrot
  - name: Twitter
    url: https://x.com/ConcernedCarro
  - name: VNDB
    url: https://vndb.org/u281841
  - name: EroSca
    url: https://erogamescape.dyndns.org/~ap2/ero/toukei_kaiseki/user_infomation.php?user=ConcernedCarrot
  - name: Backloggd
    url: https://backloggd.com/u/ConcernedCarrot/games/
  - name: MyAnimeList
    url: https://myanimelist.net/profile/ConcernedCarrot
  - name: Watcha Pedia
    url: https://pedia.watcha.com/ja-JP/users/Qgy51BD9rDxDj

url: "https://ConcernedCarrot.github.io"
baseurl: ""

theme: minima
minima:
  date_format: "%Y-%m-%d"
  skin: auto
show_excerpts: true
paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-sitemap

header_pages:
  - index.md
  - blog/index.md
  - about.md     

markdown: kramdown

google_site_verification: "tGcmRhNEoelwOxM8qZ9BtH3-iHh0ir6t07_khZlW4bQ"

giscus:
  repo: "ConcernedCarrot/ConcernedCarrot.github.io"
  repo_id: "R_kgDOQES6jg"
  category: "Announcements"
  category_id: "DIC_kwDOQES6js4Cwwfh"
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "preferred_color_scheme"
