title: "Concerned;Carrot"
description: "雑記ざっき"
lang: 
timezone:

author: ConcernedCarrot
github_username: "ConcernedCarrot"

url: "https://ConcernedCarrot.github.io"
baseurl: ""

theme: minima
minima:
  date_format: "%Y-%m-%d"
  skin: auto
show_excerpts: true
paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-sitemap

header_pages:
  - index.md
  - blog/index.md
  - about.md     

markdown: kramdown

twitter_username: "ConcernedCarro"

giscus:
  repo: "ConcernedCarrot/ConcernedCarrot.github.io"
  repo_id: "R_kgDOQES6jg"
  category: "Announcements"
  category_id: "DIC_kwDOQES6js4Cwwfh"
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  input_position: "bottom"
  theme: "preferred_color_scheme"
  lang: 
