title: ConcernedCarrot's Game Notes
description: Games I play, think about, and overanalyze
lang: ja
timezone: Asia/Tokyo
theme: minima
author:
  name: ConcernedCarrot
  email: contact@example.com
  github_username: ConcernedCarrot
minima:
  skin: auto
show_excerpts: true
paginate: 10
paginate_path: "/page:num/"
# For a user/organization site, leave both url and baseurl blank or set url to your site later.
# url: "https://concernedcarrot.github.io"
baseurl: ""
plugins:
  - jekyll-paginate