title: "Concerned;Carrot"
description: 
lang: 
timezone: 
theme: minima
author:
  name: ConcernedCarrot
  email: 
  github_username: 
minima:
  skin: auto
show_excerpts: true
paginate: 10
paginate_path: "/page:num/"
# For a user/organization site, leave both url and baseurl blank or set url to your site later.
# url: "https://concernedcarrot.github.io"
baseurl: ""
plugins:
  - jekyll-paginate
